select BANKSZ_BANKSZAMLA,
       BANKSZ_UGYFEL_ID,
       BANKSZ_BANKSZ_FELVITEL_DATUMA,
       BANKSZ_BANKSZ_MEGSZUNES_DATUMA,
       BANKSZ_TIPUS,
       BANKSZ_KONDICIOSOSZTALY,
       BANKSZ_SZAMLAALAPOT
from IM_BI.dbo.BANKSZAMLA
where BANKSZ_UGYFEL_ID IS NULL
