select KARTYA_KARTYASZAM,
       KARTYA_FELVITELDDATUMA,
       KARTYA_NYITASDATUMA,
       KARTYA_LEJARAT,
       KARTYA_BANKSZAMLASZAM,
       KARTYA_PARTNER_ID
from IM_BI.dbo.KARTYA
where KARTYA_BANKSZAMLASZAM is null